const AUDIO={bgm:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/music.wav',jump:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/bounce.mp3',coin:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/bounce.mp3',stomp:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/bounce.mp3',break:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/explosion.wav',power:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/bounce.mp3',die:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/explosion.wav',star:'https://raw.githubusercontent.com/kittykatattack/sound.js/master/sounds/bounce.mp3'};
export class AudioEngine{constructor(){this.ctx=null;this.master=null;this.sfxGain=null;this.bgmGain=null;this.buffers=new Map();this.bgmSource=null;this.muted=false;this.loading=null}
async init(muted=false,sfx=.8,bgm=.35){this.muted=muted;if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(!this.master){this.master=this.ctx.createGain();this.sfxGain=this.ctx.createGain();this.bgmGain=this.ctx.createGain();this.sfxGain.connect(this.master);this.bgmGain.connect(this.master);this.master.connect(this.ctx.destination)}this.master.gain.value=muted?0:1;this.sfxGain.gain.value=sfx;this.bgmGain.gain.value=bgm;if(this.ctx.state==='suspended')await this.ctx.resume();if(!this.loading)this.loading=this.loadAll();await this.loading;this.startMusic()}
async loadAll(){await Promise.all(Object.entries(AUDIO).map(async([name,url])=>{try{const r=await fetch(url);const data=await r.arrayBuffer();this.buffers.set(name,await this.ctx.decodeAudioData(data))}catch(e){console.warn('Audio indisponível',name)}}))}
setVolumes(sfx,bgm){if(this.sfxGain)this.sfxGain.gain.value=sfx;if(this.bgmGain)this.bgmGain.gain.value=bgm}
setMuted(v){this.muted=v;if(this.master)this.master.gain.value=v?0:1}
play(name,volume=.9,rate=1){const b=this.buffers.get(name);if(!b||!this.ctx||this.muted)return;const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=b;s.playbackRate.value=rate;g.gain.value=volume;s.connect(g).connect(this.sfxGain);s.start()}
sfx(name){this.play(name)}
startMusic(){if(this.bgmSource||!this.ctx||this.muted)return;const b=this.buffers.get('bgm');if(!b)return;const s=this.ctx.createBufferSource();s.buffer=b;s.loop=true;s.connect(this.bgmGain);s.start();this.bgmSource=s}
stopMusic(){if(this.bgmSource){try{this.bgmSource.stop()}catch{}this.bgmSource=null}}
}