import {state,PLAYER_STATES} from './state.js';import {WORLDS,parseLevel,TILE} from './levels.js';import {Input} from './input.js';import {updatePlayer,bulletMove,aabb,PHYS,moveBody} from './physics.js';import {AudioEngine} from './audio.js';import {Renderer} from './render.js';
export class Camera{constructor(){this.x=0;this.y=0;this.shake=0}update(p,world,dt){const targetX=p.body.x-130+p.body.vx*.22,targetY=p.body.y-120+p.body.vy*.05;const lerp=1-Math.pow(.001,dt);this.x+=(targetX-this.x)*lerp;this.y+=(targetY-this.y)*lerp;this.x=Math.max(0,Math.min(world.width-400,this.x));this.y=Math.max(0,Math.min(15*16-240,this.y));this.shake=Math.max(0,this.shake-dt*7)}hit(severity){this.shake=Math.max(this.shake,Math.min(12,severity))}}
export class Particles{constructor(){this.a=[]}burst(x,y,n,color='#fff',speed=90){for(let i=0;i<n;i++){const t=Math.random()*Math.PI*2,s=Math.random()*speed;this.a.push({x,y,vx:Math.cos(t)*s,vy:Math.sin(t)*s-40,life:.4+Math.random()*.5,s:1+Math.random()*2,color})}}update(dt){for(const p of this.a){p.vy+=500*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}this.a=this.a.filter(p=>p.life>0)}}
export class EnemyAI{update(e,world,p,dt){if(!e.alive)return;e.vy=Math.min(PHYS.maxFall,e.vy+PHYS.gravity*dt);const dx=p.body.x-e.x;if(e.state!=='shell'&&Math.abs(dx)<130){e.dir=Math.sign(dx)||e.dir;e.vx=e.dir*48}else e.vx=e.dir*35;const ahead=e.x+(e.dir>0?e.w+3:-3),floorY=e.y+e.h+2;const edge=!world.blocks.some(b=>b.type!=='B'&&ahead>=b.x&&ahead<=b.x+b.w&&floorY>=b.y&&floorY<=b.y+5);if(edge)e.dir*=-1;moveBody(e,dt,world)}}
export class Game{constructor(canvas){this.input=new Input();this.audio=new AudioEngine();this.renderer=new Renderer(canvas);this.camera=new Camera();this.particles=new Particles();this.enemyAI=new EnemyAI();this.bullets=[];this.world=null;this.player=null;this.levelIndex=0;this.last=0;this.acc=0;this.step=1/60;this.running=false;this.bindUI();addEventListener('resize',()=>this.renderer.resize());this.renderer.resize();this.recoverFocus()}bindUI(){const start=()=>this.start();document.getElementById('startBtn').onclick=start;document.getElementById('restartBtn').onclick=()=>this.start();document.getElementById('resumeBtn').onclick=()=>state.set({screen:'playing'});document.getElementById('nextBtn').onclick=()=>{this.levelIndex=Math.min(WORLDS.length-1,this.levelIndex+1);this.start()};}
start(){this.worldDef=WORLDS[this.levelIndex];this.world=parseLevel(this.worldDef);this.player={body:{x:this.worldDef.spawn.x,y:this.worldDef.spawn.y,w:13,h:16,vx:0,vy:0,grounded:false},state:PLAYER_STATES.IDLE,power:'small',jumpHeld:0,inv:0};this.bullets=[];this.camera.x=0;this.camera.y=0;state.set({screen:'playing',world:this.levelIndex,coins:0,time:this.worldDef.time,lives:Math.max(1,state.data.lives)});this.audio.init(state.data.muted);this.running=true;if(!this.last)this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
lose(){if(this.player.state===PLAYER_STATES.DIE)return;this.player.state=PLAYER_STATES.DIE;this.player.body.vy=-250;state.data.lives--;state.save();this.audio.sfx('die');this.camera.hit(7);setTimeout(()=>{if(state.data.lives>0)this.start();else state.set({screen:'gameover'})},850)}
win(){state.set({screen:'victory'});state.data.score+=1000;state.save();this.audio.sfx('power');this.running=false}
blockHits(){for(const b of this.world.blocks){if(b.used||b.type==='.')continue;if(aabb(this.player.body,{x:b.x,y:b.y+15,w:16,h:1})&&this.player.body.vy<0){b.bump=.1;b.used=b.type==='?';if(b.type==='?'){this.audio.sfx('coin');state.data.score+=100;state.data.coins++;this.particles.burst(b.x+8,b.y-5,8,'#fbd000',65)}else if(b.type==='#'&&this.player.power!=='small'){this.audio.sfx('break');this.particles.burst(b.x+8,b.y+8,12,'#b85c2b',120);b.type='B';b.w=0;b.h=0;}}}}
items(dt){for(const c of this.world.coins){c.t+=dt;if(!c.collected&&aabb(this.player.body,c)){c.collected=true;state.data.coins++;state.data.score+=200;this.audio.sfx('coin');this.particles.burst(c.x,c.y,7,'#fbd000',80)}}for(const it of this.world.items){if(it.hidden)continue;it.x+=0;if(aabb(this.player.body,it)){it.hidden=true;this.player.power=it.type==='flower'?'fire':'big';this.player.state=PLAYER_STATES.POWERUP;this.audio.sfx('power');this.particles.burst(this.player.body.x,this.player.body.y,15,'#ffcc00',120)}}}
enemies(dt){for(const e of this.world.enemies){this.enemyAI.update(e,this.world,this.player,dt);if(!e.alive)continue;if(aabb(this.player.body,e)&&this.player.inv<=0){if(this.player.body.vy>60&&this.player.body.y+this.player.body.h<e.y+8){e.state='shell';e.vx=0;this.player.body.vy=-260;state.data.score+=300;this.audio.sfx('stomp');this.camera.hit(3);this.particles.burst(e.x,e.y,8,'#fff',70)}else if(e.state==='shell'){e.state='patrol';e.dir=this.player.body.x<e.x?1:-1}else if(this.player.power!=='small'){this.player.power='small';this.player.inv=1.3;this.audio.sfx('stomp')}else this.lose()}}}
projectiles(dt){if(this.player.power==='fire'&&this.input.pressed('run')){this.bullets.push({x:this.player.body.x+this.player.body.w/2,y:this.player.body.y+6,w:6,h:6,vx:230,vy:-180,gravity:700,life:3});this.audio.sfx('star')}for(const b of this.bullets){bulletMove(b,dt,this.world);for(const e of this.world.enemies)if(e.alive&&aabb(b,e)){e.alive=false;b.life=0;state.data.score+=500;this.particles.burst(e.x,e.y,12,'#ffcc00',100)}}this.bullets=this.bullets.filter(b=>b.life>0&&b.y<260)}update(dt){if(state.data.screen!=='playing')return;this.input.update();state.data.time=Math.max(0,state.data.time-dt);if(state.data.time<=0){this.lose();return}this.player.inv=Math.max(0,this.player.inv-dt);updatePlayer(this.player,this.input,this.world,dt);this.blockHits();this.items(dt);this.enemies(dt);this.projectiles(dt);this.particles.update(dt);this.camera.update(this.player,this.worldDef,dt);if(this.player.body.y>260)this.lose();if(this.player.body.x>=this.worldDef.goal)this.win()}
render(){this.renderer.draw(this.world,this.player,this.camera,this.particles.a,this.bullets,state.data.time);document.getElementById('scoreDisplay').textContent=String(state.data.score).padStart(6,'0');document.getElementById('coinDisplay').textContent='x'+String(state.data.coins).padStart(2,'0');document.getElementById('timeDisplay').textContent=Math.ceil(state.data.time);document.getElementById('livesDisplay').textContent='x'+String(state.data.lives).padStart(2,'0');document.getElementById('worldDisplay').textContent=this.worldDef.id;for(const id of ['menu','pause','gameOver','victory'])document.getElementById(id).classList.toggle('hidden',state.data.screen!==id.replace('gameOver','gameover').replace('menu','menu').replace('pause','pause').replace('victory','victory'))}
loop(now){try{if(!this.running)return;let frame=Math.min(.25,(now-this.last)/1000);this.last=now;this.acc+=frame;while(this.acc>=this.step){this.update(this.step);this.acc-=this.step}this.render();requestAnimationFrame(t=>this.loop(t))}catch(err){console.error('Game loop recovered:',err);this.acc=0;this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}}
recoverFocus(){addEventListener('blur',()=>{this.input.keys.clear();this.acc=0;this.last=performance.now()});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.acc=0;this.last=performance.now()}else this.last=performance.now()})}}
